In [ ]:
#import library
import numpy as np
import pandas as pd
from sklearn import tree

In [ ]:
#read data
irisDataset = pd.read_csv('credit_risk_dataset.csv')

In [ ]:
irisDataset.head()

person_age  person_income person_home_ownership  person_emp_length  \
0          22          59000                  RENT              123.0   
1          21           9600                   OWN                5.0   
2          25           9600              MORTGAGE                1.0   
3          23          65500                  RENT                4.0   
4          24          54400                  RENT                8.0   

  loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
0    PERSONAL          D      35000          16.02            1   
1   EDUCATION          B       1000          11.14            0   
2     MEDICAL          C       5500          12.87            1   
3     MEDICAL          C      35000          15.23            1   
4     MEDICAL          C      35000          14.27            1   

   loan_percent_income cb_person_default_on_file  cb_person_cred_hist_length  
0                 0.59                         Y                           3  
1                 0.10                         N                           2  
2                 0.57                         N                           3  
3                 0.53                         N                           2  
4                 0.55                         Y                           4

In [ ]:
# Membuat peta nilai untuk transformasi
mapping = {'OWN': 0, 'RENT': 1, 'MORTGAGE': 2}
# Mengganti nilai dalam kolom 'Home_Ownership' menggunakan peta nilai
irisDataset['person_home_ownership'] = irisDataset['person_home_ownership'].map(mapping)

# Membuat peta nilai untuk transformasi
mapping = {'EDUCATION': 0, 'MEDICAL': 1, 'VENTURE': 2, 'PERSONAL':3, 'DEBTCONSOLIDATION':4}
# Mengganti nilai dalam kolom 'Home_Ownership' menggunakan peta nilai
irisDataset['loan_intent'] = irisDataset['loan_intent'].map(mapping)

# Membuat peta nilai untuk transformasi
mapping = {'A': 0, 'B': 1, 'C': 2, 'D':3, 'E':4}
# Mengganti nilai dalam kolom 'Home_Ownership' menggunakan peta nilai
irisDataset['loan_grade'] = irisDataset['loan_grade'].map(mapping)

# Membuat peta nilai untuk transformasi
mapping = {'N': 0, 'Y': 1}
# Mengganti nilai dalam kolom 'Home_Ownership' menggunakan peta nilai
irisDataset['cb_person_default_on_file'] = irisDataset['cb_person_default_on_file'].map(mapping)

In [ ]:
print(irisDataset)
len(irisDataset)

       person_age  person_income  person_home_ownership  person_emp_length  \
0              22          59000                    1.0              123.0   
1              21           9600                    0.0                5.0   
2              25           9600                    2.0                1.0   
3              23          65500                    1.0                4.0   
4              24          54400                    1.0                8.0   
...           ...            ...                    ...                ...   
32576          57          53000                    2.0                1.0   
32577          54         120000                    2.0                4.0   
32578          65          76000                    1.0                3.0   
32579          56         150000                    2.0                5.0   
32580          66          42000                    1.0                2.0   

       loan_intent  loan_grade  loan_amnt  loan_int_rate  loan_

32581

In [ ]:
# Pengecekan Missing Value
print(" Pengecekan Missing Value ".center(75 ,"="))
print(irisDataset.isnull().sum())
print("===========================================================================")
#setelah dilakukan pengecekan missing valaue, tidak ditemukan adanya missing value

========================= Pengecekan Missing Value ========================
person_age                       0
person_income                    0
person_home_ownership          107
person_emp_length              895
loan_intent                   3605
loan_grade                     305
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64


In [ ]:
irisDataset.fillna(method='backfill', inplace=True)


In [ ]:
print(irisDataset.isnull().sum())

person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_status                   0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
dtype: int64


In [ ]:
#mengubah dataframe ke array numpy
irisDataset= irisDataset.to_numpy()

In [ ]:
print(irisDataset)
len(irisDataset)

[[2.2e+01 5.9e+04 1.0e+00 ... 5.9e-01 1.0e+00 3.0e+00]
 [2.1e+01 9.6e+03 0.0e+00 ... 1.0e-01 0.0e+00 2.0e+00]
 [2.5e+01 9.6e+03 2.0e+00 ... 5.7e-01 0.0e+00 3.0e+00]
 ...
 [6.5e+01 7.6e+04 1.0e+00 ... 4.6e-01 0.0e+00 2.8e+01]
 [5.6e+01 1.5e+05 2.0e+00 ... 1.0e-01 0.0e+00 2.6e+01]
 [6.6e+01 4.2e+04 1.0e+00 ... 1.5e-01 0.0e+00 3.0e+01]]


32581

In [ ]:
#Membagi dataset menjadi data training dan data testing
dataTraining = np.concatenate((irisDataset[0:20000,:], irisDataset[22500:30000,:]), axis=0)
dataTesting =np.concatenate((irisDataset[20000:22500,:], irisDataset[30000:32581,:]), axis=0)

In [ ]:
print(dataTraining)
len(dataTraining)

[[2.2e+01 5.9e+04 1.0e+00 ... 5.9e-01 1.0e+00 3.0e+00]
 [2.1e+01 9.6e+03 0.0e+00 ... 1.0e-01 0.0e+00 2.0e+00]
 [2.5e+01 9.6e+03 2.0e+00 ... 5.7e-01 0.0e+00 3.0e+00]
 ...
 [3.9e+01 4.3e+04 2.0e+00 ... 1.5e-01 0.0e+00 1.4e+01]
 [4.0e+01 4.3e+04 2.0e+00 ... 6.0e-02 0.0e+00 1.4e+01]
 [4.1e+01 4.7e+04 1.0e+00 ... 1.1e-01 0.0e+00 1.1e+01]]


27500

In [ ]:
print(dataTesting)
len(dataTesting)

[[3.3000e+01 5.3000e+04 1.0000e+00 ... 7.0000e-02 0.0000e+00 5.0000e+00]
 [2.9000e+01 5.4996e+04 1.0000e+00 ... 7.0000e-02 0.0000e+00 5.0000e+00]
 [3.3000e+01 5.5000e+04 1.0000e+00 ... 7.0000e-02 0.0000e+00 6.0000e+00]
 ...
 [6.5000e+01 7.6000e+04 1.0000e+00 ... 4.6000e-01 0.0000e+00 2.8000e+01]
 [5.6000e+01 1.5000e+05 2.0000e+00 ... 1.0000e-01 0.0000e+00 2.6000e+01]
 [6.6000e+01 4.2000e+04 1.0000e+00 ... 1.5000e-01 0.0000e+00 3.0000e+01]]


5081

In [ ]:
#memecah dataset ke input dan label
inputTraining = dataTraining[:,0:12]
inputTesting = dataTesting[:,0:12]
labelTraining = dataTraining[:, 9]
labelTesting = dataTesting[:, 9]
print(labelTraining)
print("===================================")
print(labelTesting)

[0.59 0.1  0.57 ... 0.15 0.06 0.11]
[0.07 0.07 0.07 ... 0.46 0.1  0.15]


In [ ]:
#Mendefinisikan Decision tree classifier
model = tree.DecisionTreeClassifier()

In [ ]:
#training model
model = model.fit(inputTraining, labelTraining)


ValueError: ignored

In [ ]:
#Memprediksi input data testing
hasilPrediksi = model.predict(inputTesting)
print("Label sebenarnya : ", labelTesting)
print("Label prediksi : ", hasilPrediksi )

Label sebenarnya :  [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 0 0 1 1 1
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Label prediksi :  [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
#menghitung akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("prediksi benar :", prediksiBenar, "data")
print("prediksi salah :", prediksiSalah, "data")
print("akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah)*100, "%")

prediksi benar : 91 data
prediksi salah : 9 data
akurasi : 91.0 %
