In [ ]:
#import library
import numpy as np
import pandas as pd
from sklearn import tree

In [ ]:
#read data
irisDataset = pd.read_csv('survey lung cancer.csv')

In [ ]:
irisDataset.head()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0       0   69        1               2        2              1   
1       0   74        2               1        1              1   
2       1   59        1               1        1              2   
3       0   63        2               2        2              1   
4       1   63        1               2        1              1   

   CHRONIC DISEASE  FATIGUE  ALLERGY  WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                1        2        1         2                  2         2   
1                2        2        2         1                  1         1   
2                1        2        1         2                  1         2   
3                1        1        1         1                  2         1   
4                1        1        1         2                  1         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  LUNG_CANCER  
0                    2                      2           2            0  
1                    2                      2           2            0  
2                    2                      1           2            1  
3                    1                      2           2            1  
4                    2                      1           1            1

In [ ]:
#mengubah dataframe ke array numpy
irisDataset= irisDataset.to_numpy()

In [ ]:
print(irisDataset)
len(irisDataset)

[[ 0 69  1 ...  2  2  0]
 [ 0 74  2 ...  2  2  0]
 [ 1 59  1 ...  1  2  1]
 ...
 [ 0 58  2 ...  1  2  0]
 [ 0 67  2 ...  1  2  0]
 [ 0 62  1 ...  2  1  0]]


309

In [ ]:
#Membagi dataset menjadi data training dan data testing
dataTraining = np.concatenate((irisDataset[0:50,:], irisDataset[100:259,:]), axis=0)
dataTesting =np.concatenate((irisDataset[50:100,:], irisDataset[259:309,:]), axis=0)

In [ ]:
print(dataTraining)
len(dataTraining)

[[ 0 69  1 ...  2  2  0]
 [ 0 74  2 ...  2  2  0]
 [ 1 59  1 ...  1  2  1]
 ...
 [ 0 60  2 ...  1  2  0]
 [ 0 64  2 ...  1  2  0]
 [ 0 70  2 ...  1  2  0]]


209

In [ ]:
print(dataTesting)
len(dataTesting)

[[ 1 56  1 ...  1  2  0]
 [ 0 63  2 ...  1  1  0]
 [ 1 54  2 ...  2  2  0]
 ...
 [ 0 58  2 ...  1  2  0]
 [ 0 67  2 ...  1  2  0]
 [ 0 62  1 ...  2  1  0]]


100

In [ ]:
#memecah dataset ke input dan label
inputTraining = dataTraining[:,0:15]
inputTesting = dataTesting[:,0:15]
labelTraining = dataTraining[:, 15]
labelTesting = dataTesting[:, 15]
print(labelTraining)
print("===================================")
print(labelTesting)

[0 0 1 1 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 1 1 0 1 0 1 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 0 0 1 1 1
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
#Mendefinisikan Decision tree classifier
model = tree.DecisionTreeClassifier()

In [ ]:
#training model
model = model.fit(inputTraining, labelTraining)


In [ ]:
#Memprediksi input data testing
hasilPrediksi = model.predict(inputTesting)
print("Label sebenarnya : ", labelTesting)
print("Label prediksi : ", hasilPrediksi )

Label sebenarnya :  [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 0 0 1 1 1
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Label prediksi :  [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
#menghitung akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("prediksi benar :", prediksiBenar, "data")
print("prediksi salah :", prediksiSalah, "data")
print("akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah)*100, "%")

prediksi benar : 91 data
prediksi salah : 9 data
akurasi : 91.0 %
