In [ ]:
#Import modul
from pandas.core.frame import DataFrame
import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import OrdinalEncoder
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
import scipy.stats as stats
import numpy as np
import pickle
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

#Membaca data
data = pd.read_csv("Qris.csv")
df = pd.DataFrame(data)
print(df)

#Pengecekkan missing value -- tidak ada missing value setelah code dijalankan
print("===================================================================================================")
print("Pengecekkan missing value")
dataMiss = df.isna().sum()
print(dataMiss)

df = pd.DataFrame(data)

               Timestamp                        Nama  Umur Jenis Kelamin  \
0    02/10/2023 15:16:19                       Abram    20     Laki-laki   
1    02/10/2023 15:39:19                   Airlangga    20     Laki-laki   
2    02/10/2023 15:45:11                       Wangi    20     Perempuan   
3    02/10/2023 15:51:21   Muhammad Rifki Ubaedillah    24     Laki-laki   
4    02/10/2023 16:01:56  Ni Kadek Rosa Amalia Putri    21     Perempuan   
..                   ...                         ...   ...           ...   
110  11/10/2023 18:07:55                 Dwi Sucipto    22     Laki-laki   
111  12/10/2023 21:37:13                        Lina    26     Perempuan   
112   13/10/2023 9:30:12                        aufa    21     Perempuan   
113  13/10/2023 14:05:16                        Fika    21     Perempuan   
114  13/10/2023 17:02:33                        Tyas    22     Perempuan   

    Status pekerjaan Pendapatan per bulan  \
0       Sedang studi   Kurang dari 2 juta 

In [ ]:
df.rename(columns={'Apakah Anda mengetahui apa itu QRIS?':'Atensi_qris',
                   'Sejak kapan Anda mengetahui QRIS?': 'Atensi_pertama_QRIS',
                   'Seberapa sering Anda menggunakan QRIS dalam transaksi sehari-hari?': 'Frekuensi',
                   'Bagaimana pengalaman Anda menggunakan QRIS dalam bertransaksi?':'Pengalaman_pengguna' ,
                   'Apakah Anda merasa lebih efisien menggunakan QRIS dibandingkan dengan metode pembayaran lain?':'Efisiensi',
                   'Seberapa percaya Anda terhadap keamanan QRIS dalam melakukan transaksi?': 'Kepercayaan_pengguna',
                   'Apakah Anda pernah mengalami masalah keamanan (seperti kebocoran pin) saat menggunakan QRIS?':'keamanan',
                   'Apakah penggunaan QRIS meningkatkan kecenderungan Anda untuk berbelanja secara impulsif?':'Impulsif',
                   'Apakah Anda cenderung menghabiskan lebih banyak uang setelah menggunakan QRIS?':'Kencenderungan_menghabiskan_uang',
                   'Bagaimana menurut Anda pengaruh QRIS terhadap pola pengeluaran bulanan Anda?':'Pengaruh_QRIS_thd_Pengeluaran'}, inplace=True)
df.head()

Timestamp                        Nama  Umur Jenis Kelamin  \
0  02/10/2023 15:16:19                       Abram    20     Laki-laki   
1  02/10/2023 15:39:19                   Airlangga    20     Laki-laki   
2  02/10/2023 15:45:11                       Wangi    20     Perempuan   
3  02/10/2023 15:51:21   Muhammad Rifki Ubaedillah    24     Laki-laki   
4  02/10/2023 16:01:56  Ni Kadek Rosa Amalia Putri    21     Perempuan   

  Status pekerjaan Pendapatan per bulan Atensi_qris Atensi_pertama_QRIS  \
0     Sedang studi   Kurang dari 2 juta          Ya       Baru-baru ini   
1     Sedang studi   Kurang dari 2 juta          Ya       Baru-baru ini   
2     Sedang studi   Kurang dari 2 juta          Ya          Sejak 2019   
3          Lainnya   Kurang dari 2 juta          Ya          Sejak 2019   
4     Sedang studi   Kurang dari 2 juta          Ya       Baru-baru ini   

   Frekuensi  Pengalaman_pengguna    Efisiensi  Kepercayaan_pengguna  \
0          5                    4  Tidak yakin                     3   
1          5                    5           Ya                     5   
2          4                    4           Ya                     3   
3          5                    4  Tidak yakin                     2   
4          5                    5           Ya                     5   

      keamanan     Impulsif Kencenderungan_menghabiskan_uang  \
0        Tidak        Tidak                            Tidak   
1        Tidak           Ya                               Ya   
2        Tidak           Ya                               Ya   
3        Tidak           Ya                               Ya   
4  Tidak yakin  Tidak yakin                               Ya   

   Pengaruh_QRIS_thd_Pengeluaran  
0                              2  
1                              2  
2                              3  
3                              3  
4                              3

In [ ]:
df['Jenis Kelamin'] = df['Jenis Kelamin'].replace({'Laki-laki' : 0, "Perempuan" : 1})
df['Status pekerjaan'] = df['Status pekerjaan'].replace({'Sedang studi' : 0, "Bekerja" : 1, "Lainnya" : 2})
df['Pendapatan per bulan'] = df['Pendapatan per bulan'].replace({'Kurang dari 2 juta' : 0, "2-5 juta" : 1, "5-10 juta" :2, "Lebih dari 10 juta" :3})
df['Atensi_qris'] = df['Atensi_qris'].replace({'Tidak' : 0, "Ya" : 1})
df['Atensi_pertama_QRIS'] = df['Atensi_pertama_QRIS'].replace({'Baru-baru ini' : 0, "Sejak 2019" : 1})
df['Efisiensi'] = df['Efisiensi'].replace({'Tidak' : 0, "Tidak yakin" : 1, "Ya" : 2})
df['keamanan'] = df['keamanan'].replace({'Tidak' : 0, "Tidak yakin" : 1, "Ya" : 2})
df['Impulsif'] = df['Impulsif'].replace({'Tidak' : 0, "Tidak yakin" : 1, "Ya" : 2})
df['Kencenderungan_menghabiskan_uang'] = df['Kencenderungan_menghabiskan_uang'].replace({'Tidak' : 0, "Tidak yakin" : 1, "Ya" : 2})

df.head()

Timestamp                        Nama  Umur  Jenis Kelamin  \
0  02/10/2023 15:16:19                       Abram    20              0   
1  02/10/2023 15:39:19                   Airlangga    20              0   
2  02/10/2023 15:45:11                       Wangi    20              1   
3  02/10/2023 15:51:21   Muhammad Rifki Ubaedillah    24              0   
4  02/10/2023 16:01:56  Ni Kadek Rosa Amalia Putri    21              1   

   Status pekerjaan  Pendapatan per bulan  Atensi_qris  Atensi_pertama_QRIS  \
0                 0                     0            1                    0   
1                 0                     0            1                    0   
2                 0                     0            1                    1   
3                 2                     0            1                    1   
4                 0                     0            1                    0   

   Frekuensi  Pengalaman_pengguna  Efisiensi  Kepercayaan_pengguna  keamanan  \
0          5                    4          1                     3         0   
1          5                    5          2                     5         0   
2          4                    4          2                     3         0   
3          5                    4          1                     2         0   
4          5                    5          2                     5         1   

   Impulsif  Kencenderungan_menghabiskan_uang  Pengaruh_QRIS_thd_Pengeluaran  
0         0                                 0                              2  
1         2                                 2                              2  
2         2                                 2                              3  
3         2                                 2                              3  
4         1                                 2                              3

In [ ]:
# Menggunakan OrdinalEncoder untuk mengubah data ordinal menjadi angka
ordinal_encoder = OrdinalEncoder()
df['Jenis Kelamin_encoded'] = ordinal_encoder.fit_transform(df[['Jenis Kelamin']])
df['Status pekerjaan_encoded'] = ordinal_encoder.fit_transform(df[['Status pekerjaan']])
df['Pendapatan per bulan_encoded'] = ordinal_encoder.fit_transform(df[['Pendapatan per bulan']])
df['Atensi_qris_encoded'] = ordinal_encoder.fit_transform(df[['Atensi_qris']])
df['Atensi_pertama_QRIS_encoded'] = ordinal_encoder.fit_transform(df[['Atensi_pertama_QRIS']])
df['Frekuensi_encoded'] = ordinal_encoder.fit_transform(df[['Frekuensi']])
df['Pengalaman_pengguna_encoded'] = ordinal_encoder.fit_transform(df[['Pengalaman_pengguna']])
df['Efisiensi_encoded'] = ordinal_encoder.fit_transform(df[['Efisiensi']])
df['Kepercayaan_pengguna_encoded'] = ordinal_encoder.fit_transform(df[['Kepercayaan_pengguna']])
df['keamanan_encoded'] = ordinal_encoder.fit_transform(df[['keamanan']])
df['Impulsif_encoded'] = ordinal_encoder.fit_transform(df[['Impulsif']])
df['Kencenderungan_menghabiskan_uang_encoded'] = ordinal_encoder.fit_transform(df[['Kencenderungan_menghabiskan_uang']])
df['Pengaruh_QRIS_thd_Pengeluaran_encoded'] = ordinal_encoder.fit_transform(df[['Pengaruh_QRIS_thd_Pengeluaran']])

In [ ]:
# Pemilihan fitur dengan SelectKBest dan chi-squared sebagai skor
X = df[['Umur','Jenis Kelamin','Status pekerjaan_encoded','Pendapatan per bulan_encoded','Atensi_qris_encoded',
        'Atensi_pertama_QRIS_encoded','Frekuensi_encoded','Pengalaman_pengguna_encoded','Efisiensi_encoded','Kepercayaan_pengguna_encoded',
        'keamanan_encoded','Impulsif_encoded','Kencenderungan_menghabiskan_uang_encoded','Pengaruh_QRIS_thd_Pengeluaran_encoded']]
y = df['Impulsif_encoded']
# Pilih 7 fitur terbaik
k_best = SelectKBest(score_func=chi2, k=7)
X_new = k_best.fit_transform(X, y)

# Tampilkan fitur terpilih
selected_features = X.columns[k_best.get_support()]
print("Fitur terpilih:", selected_features)

Fitur terpilih: Index(['Status pekerjaan_encoded', 'Pendapatan per bulan_encoded',
       'Frekuensi_encoded', 'keamanan_encoded', 'Impulsif_encoded',
       'Kencenderungan_menghabiskan_uang_encoded',
       'Pengaruh_QRIS_thd_Pengeluaran_encoded'],
      dtype='object')


In [ ]:
#Mendefinisikan ulang data dengan fitur hasil seleksi
data = df[['Status pekerjaan_encoded', 'Pendapatan per bulan_encoded',
       'Frekuensi_encoded', 'keamanan_encoded',
       'Kencenderungan_menghabiskan_uang_encoded',
       'Pengaruh_QRIS_thd_Pengeluaran_encoded','Impulsif_encoded']]
df = pd.DataFrame(data)
df.head()

Status pekerjaan_encoded  Pendapatan per bulan_encoded  Frekuensi_encoded  \
0                       0.0                           0.0                4.0   
1                       0.0                           0.0                4.0   
2                       0.0                           0.0                3.0   
3                       2.0                           0.0                4.0   
4                       0.0                           0.0                4.0   

   keamanan_encoded  Kencenderungan_menghabiskan_uang_encoded  \
0               0.0                                       0.0   
1               0.0                                       2.0   
2               0.0                                       2.0   
3               0.0                                       2.0   
4               1.0                                       2.0   

   Pengaruh_QRIS_thd_Pengeluaran_encoded  Impulsif_encoded  
0                                    1.0               0.0  
1                                    1.0               2.0  
2                                    2.0               2.0  
3                                    2.0               2.0  
4                                    2.0               1.0

In [ ]:
#Deteksi outlier-- tidak ada outlier setelah code dijalankan
df = df[(np.abs(stats.zscore(df)) < 3).all(axis=1)]
variabel = ('Status pekerjaan_encoded', 'Pendapatan per bulan_encoded',
       'Frekuensi_encoded', 'keamanan_encoded',
       'Kencenderungan_menghabiskan_uang_encoded',
       'Pengaruh_QRIS_thd_Pengeluaran_encoded','Impulsif_encoded',)
outliers = []
def detect_outlier(df):

    threshold = 3
    mean_1 = np.mean(df)
    std_1 = np.std(df)

    for y in df:
        z_score= (y - mean_1)/std_1
        if np.abs(z_score) > threshold:
            outliers.append(y)
    return outliers

for var in variabel:
    outlier_datapoints = detect_outlier(df[var])
    print("Outlier ", var, " = ", outlier_datapoints)

print()

Outlier  Status pekerjaan_encoded  =  []
Outlier  Pendapatan per bulan_encoded  =  []
Outlier  Frekuensi_encoded  =  []
Outlier  keamanan_encoded  =  []
Outlier  Kencenderungan_menghabiskan_uang_encoded  =  []
Outlier  Pengaruh_QRIS_thd_Pengeluaran_encoded  =  []
Outlier  Impulsif_encoded  =  []



In [ ]:
#mengubah dataframe ke array numpy
df= df.to_numpy()

In [ ]:
######################## klasifikasi ##########################################

#Membagi dataset menjadi data training dan data testing
dataTraining = np.concatenate((df[0:40,:], df[50:80,:]), axis=0)
dataTesting =np.concatenate((df[40:50,:], df[80:107,:]), axis=0)


In [ ]:
print(dataTesting)
len(dataTesting)

[[0. 0. 4. 0. 2. 2. 2.]
 [0. 0. 4. 0. 2. 2. 2.]
 [2. 0. 2. 1. 1. 1. 1.]
 [0. 0. 4. 0. 0. 1. 1.]
 [0. 1. 0. 0. 0. 2. 0.]
 [0. 0. 3. 0. 0. 1. 0.]
 [0. 0. 2. 0. 0. 1. 0.]
 [0. 0. 3. 0. 1. 1. 0.]
 [0. 0. 4. 0. 2. 2. 2.]
 [0. 0. 4. 0. 2. 2. 2.]
 [0. 0. 2. 0. 1. 1. 2.]
 [0. 0. 3. 1. 2. 2. 2.]
 [0. 1. 2. 1. 2. 2. 2.]
 [1. 1. 2. 1. 0. 1. 0.]
 [0. 0. 3. 0. 1. 1. 2.]
 [0. 0. 3. 0. 2. 2. 2.]
 [0. 0. 4. 0. 2. 2. 2.]
 [0. 0. 2. 0. 0. 1. 0.]
 [0. 0. 4. 0. 0. 1. 0.]
 [1. 1. 1. 1. 0. 1. 0.]
 [0. 0. 2. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0.]
 [0. 1. 3. 0. 2. 2. 2.]
 [0. 0. 1. 0. 1. 1. 1.]
 [0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 4. 0. 2. 1. 2.]
 [1. 1. 0. 0. 1. 1. 2.]
 [1. 1. 0. 1. 0. 1. 0.]
 [0. 0. 2. 0. 0. 1. 2.]
 [0. 0. 4. 0. 1. 1. 2.]
 [0. 1. 4. 0. 2. 1. 2.]
 [0. 0. 2. 1. 2. 2. 2.]
 [0. 0. 2. 0. 0. 1. 2.]
 [2. 0. 4. 0. 2. 1. 1.]
 [0. 0. 1. 0. 1. 1. 1.]
 [0. 0. 1. 0. 0. 1. 0.]
 [0. 1. 4. 1. 0. 1. 0.]]


37

In [ ]:
#memecah dataset ke input dan label
inputTraining = dataTraining[:,0:6]
inputTesting = dataTesting[:,0:6]
labelTraining = dataTraining[:, 6]
labelTesting = dataTesting[:, 6]
print(labelTraining)
print("===================================")
print(labelTesting)

[0. 2. 2. 2. 1. 0. 2. 1. 2. 0. 2. 2. 2. 0. 0. 0. 0. 0. 0. 2. 0. 1. 2. 0.
 2. 2. 0. 0. 0. 2. 0. 2. 0. 2. 0. 0. 0. 1. 1. 2. 2. 2. 1. 2. 1. 2. 2. 0.
 0. 1. 2. 0. 2. 1. 0. 1. 0. 0. 2. 0. 2. 2. 2. 2. 0. 0. 1. 2. 0. 0.]
[2. 2. 1. 1. 0. 0. 0. 0. 2. 2. 2. 2. 2. 0. 2. 2. 2. 0. 0. 0. 0. 0. 2. 1.
 0. 2. 2. 0. 2. 2. 2. 2. 2. 1. 1. 0. 0.]


In [ ]:
#Mendefinisikan random forest
classifier = RandomForestClassifier()
#training model
classifier = classifier.fit(inputTraining, labelTraining)


# Membuat prediksi
hasilPrediksi = classifier.predict(inputTesting)
print("Label sebenarnya : ", labelTesting)
print("Label prediksi : ", hasilPrediksi )

Label sebenarnya :  [2. 2. 1. 1. 0. 0. 0. 0. 2. 2. 2. 2. 2. 0. 2. 2. 2. 0. 0. 0. 0. 0. 2. 1.
 0. 2. 2. 0. 2. 2. 2. 2. 2. 1. 1. 0. 0.]
Label prediksi :  [2. 2. 0. 1. 0. 0. 0. 0. 2. 2. 0. 2. 2. 2. 0. 2. 2. 0. 1. 0. 0. 0. 2. 1.
 0. 2. 0. 0. 0. 1. 2. 2. 0. 2. 1. 0. 0.]


In [ ]:
# Evaluasi model
from sklearn.metrics import accuracy_score, classification_report
accuracy = accuracy_score(labelTesting, hasilPrediksi)
print(f'Accuracy: {accuracy}')

# Laporan klasifikasi
print(classification_report(labelTesting, hasilPrediksi))

Accuracy: 0.7297297297297297
              precision    recall  f1-score   support

         0.0       0.67      0.86      0.75        14
         1.0       0.60      0.60      0.60         5
         2.0       0.86      0.67      0.75        18

    accuracy                           0.73        37
   macro avg       0.71      0.71      0.70        37
weighted avg       0.75      0.73      0.73        37



In [ ]:
pickle.dump(classifier, open("model.pkl", "wb"))